### ISSUE TITLE
Zero decimals in scientific notation not highlighted consistently

### ISSUE THREAD

**Issue by PaulRBerg** [juanfranblanco/vscode-solidity#378]
The following number literal formats have a yellow-greenish tint:

- `1234`
- `1_234`
- `1.234e18`

But simply by introducing a `0` after `1.`, the highlight color changes to white:

- `1.0234e18`

This is a bit misleading because it makes it seem as though there is something qualitatively different with numbers that have leading zeroes after the dot. But there isn't anything different.

<img width="407" alt="VSCode screenshot Solidity number literals" src="https://user-images.githubusercontent.com/8782666/202893291-066906d5-8bc2-450d-ac14-7db6fc0ffd9d.png">

**Comment by juanfranblanco** [comment]
Fixed in latest
![image](https://user-images.githubusercontent.com/562371/223424382-5d8e8b9c-b3ab-486c-ac2e-51d3b0b257ff.png)
![image](https://user-images.githubusercontent.com/562371/223424432-a930f2ff-cbbb-42db-a334-43ff3a4856fb.png)

**Comment by PaulRBerg** [comment]
@juanfranblanco I'm afraid this still doesn't work as expected. See this [code](https://github.com/PaulRBerg/prb-math/blob/3eeafb6ae9b55e2e30302491ce6c2e0f70798d00/test/sd59x18/math/div/div.t.sol#L107-L112):

<img width="686" alt="Screenshot 2023-03-07 at 6 22 14 PM" src="https://user-images.githubusercontent.com/8782666/223484363-2a1a7ff9-f3fd-4126-9aa0-11eb414c49a1.png">
